// ============================================================================
// Seeding service — populates cars, tracks, and benchmark tiers. Tracks +
// benchmarks come from REAL "Ohne Speed" data (src/data/*.json, generated by
// scripts/parse-ohne-speed.mjs). Idempotent: every write upserts.
// Invoked by POST /api/seed and scripts/seed.mjs.
// ============================================================================

import type { Condition, RacingClass } from "@/types";
import benchmarksData from "@/data/benchmarks.json";
import tracksData from "@/data/tracks.json";
import type { Store } from "./db/types";
import { SEED_CARS } from "./seed-data";

interface BenchmarkRow {
  track: string;
  class: string;
  condition: string;
  patch_version: string | null;
  data_readiness_pct: number;
  alien_time: number;
  competitive_time: number;
  good_time: number;
  midpack_time: number;
  tail_ender_time: number;
  offline_time: number;
}

interface TrackRow {
  name: string;
  layout_id: string | null;
  country: string | null;
}

export interface SeedSummary {
  cars: number;
  tracks: number;
  benchmarks: number;
}

export async function seedDatabase(store: Store): Promise<SeedSummary> {
  await store.init();

  for (const c of SEED_CARS) {
    await store.createCar(c.name, c.category);
  }

  // Tracks from the real sheet (29 circuit/layout variants).
  const tracks = tracksData as unknown as TrackRow[];
  const trackIdByName = new Map<string, number>();
  for (const t of tracks) {
    const track = await store.createTrack(t.name, t.layout_id, t.country);
    trackIdByName.set(t.name, track.id);
  }

  // Real benchmark tiers (Dry hotlap/race-pace; 5 classes).
  let benchmarks = 0;
  for (const b of benchmarksData as unknown as BenchmarkRow[]) {
    const trackId = trackIdByName.get(b.track);
    if (!trackId) continue;
    await store.upsertBenchmark({
      track_id: trackId,
      class: b.class as RacingClass,
      condition: b.condition as Condition,
      alien_time: b.alien_time,
      competitive_time: b.competitive_time,
      good_time: b.good_time,
      good_102_time: null, // seed data predates the 102%/104% columns; a real sync fills these in
      midpack_time: b.midpack_time,
      midpack_104_time: null,
      tail_ender_time: b.tail_ender_time,
      offline_time: b.offline_time,
      data_readiness_pct: b.data_readiness_pct,
      patch_version: b.patch_version,
    });
    benchmarks++;
  }

  return { cars: SEED_CARS.length, tracks: tracks.length, benchmarks };
}
