// ============================================================================
// Seed car roster. Tracks + benchmark tiers now come from REAL "Ohne Speed"
// data in src/data/*.json (generated by scripts/parse-ohne-speed.mjs); see
// seed.ts. The sheet only lists the fastest car per track, not the full grid,
// so the roster is maintained here.
// ============================================================================

import type { CarCategory } from "@/types";

export interface SeedCar {
  name: string;
  category: CarCategory;
}

export const SEED_CARS: SeedCar[] = [
  // Hypercar (LMH / LMDh)
  { name: "Toyota GR010 Hybrid", category: "Hypercar" },
  { name: "Ferrari 499P", category: "Hypercar" },
  { name: "Porsche 963", category: "Hypercar" },
  { name: "Cadillac V-Series.R", category: "Hypercar" },
  { name: "BMW M Hybrid V8", category: "Hypercar" },
  { name: "Peugeot 9X8", category: "Hypercar" },
  { name: "Alpine A424", category: "Hypercar" },
  { name: "Lamborghini SC63", category: "Hypercar" },
  { name: "Aston Martin Valkyrie", category: "Hypercar" },
  { name: "Genesis GMR-001", category: "Hypercar" },
  // GT3 (LMGT3)
  { name: "Porsche 992 GT3 R", category: "GT3" },
  { name: "Ferrari 296 GT3", category: "GT3" },
  { name: "Chevrolet Corvette Z06 GT3.R", category: "GT3" },
  { name: "Aston Martin Vantage AMR GT3", category: "GT3" },
  { name: "BMW M4 GT3", category: "GT3" },
  { name: "Lamborghini Huracán GT3 EVO II", category: "GT3" },
  { name: "McLaren 720S GT3 EVO", category: "GT3" },
  { name: "Mercedes-AMG GT3", category: "GT3" },
  { name: "Ford Mustang GT3", category: "GT3" },
  { name: "Lexus RC F GT3", category: "GT3" },
  // LMP2
  { name: "Oreca 07 LMP2", category: "LMP2" },
  // LMP3
  { name: "Ligier JS P320", category: "LMP3" },
  { name: "Duqueine D09", category: "LMP3" },
  { name: "Ginetta G61-LT-P3", category: "LMP3" },
];
